### ISSUE TITLE
v0.0.6?

### ISSUE THREAD

**Issue by dashed** [contain-rs/enum-set#17]
I'm confused on which commit denotes v0.0.6 on this repo: https://crates.io/crates/enum-set

Cargo.toml is at v0.0.4

**Comment by apasel422** [comment]
Looks like @Gankro bumped the version to 0.0.5 in response to #11, but possibly only made the commit locally before publishing instead of pushing to the remote.

**Comment by dashed** [comment]
Ah I see, so master on github is v0.0.6?

**Comment by rnewman** [comment]
I bumped the repo version to 0.0.6 in #20.

**Comment by Gankra** [comment]
Actually that's 0.0.7 now. idk what happened with the version numbers. Pushed up my local repo.

**Comment by dashed** [comment]
Thanks! :)
