### ISSUE TITLE
Send and Sync

### ISSUE THREAD

**Issue by bch29** [contain-rs/enum-set#19]
Is there a reason why the `EnumSet` struct definition contains `PhantomData<*mut E>` instead of `PhantomData<E>`? The former means that every `EnumSet` isn't `Send` or `Sync`, which is quite limiting.

**Comment by apasel422** [comment]
I don't think there's a reason for this. The marker should probably be changed to `PhantomData<E>`.

**Comment by rnewman** [comment]
Fixed by #20.
