### ISSUE TITLE
Any chance of making CLike use usize instead of u32 so that enum-map's Enum can inherit from it?

### ISSUE THREAD

**Issue by SilensAngelusNex** [contain-rs/enum-set#24]
Since the the both traits convert an `enum` into an unsigned int and back, it would be nice to merge that functionality into one place. It would also let you piggyback off `enum-set`'s derive.

**Comment by Gankra** [comment]
enum-set uses u32 so that its representable states aren't platform-dependent, and this won't change. We have no relation to enum-map.
